config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users

  resources :logins

  resources :articles do
    resources :comments
  end

  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @article = Article.all
  end

  def show
    @article = Article.find_by_id(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find_by_id(params[:id])
  end
  
  def create
   @article = Article.new(article_params)
   
   @user = User.find_by_name(session[:current_user_id])
   @article.user_id = @user.id
   
   if @article.save
     redirect_to @article
   else
     render 'new'
   end
  end
  
  def update
    @article = Article.find_by_id(params[:id])
    
    if @article .update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find_by_id(params[:id])
    @article.destroy
    
    redirect_to articles_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret"

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.js
      format.json { render json: @comment}
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.js
      format.json { render json: @comment}
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
  
  def login
    @user = User.find_by_name_and_pwd(params[:name], params[:pwd])
    
    if @user
      session[:current_user_id] = params[:name]
      redirect_to articles_path
    else
      render 'index'
    end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end
  
  def create
    @user = User.find_by_name_and_pwd(params[:name], params[:pwd])
    
    if @user
      session[:current_user_id] = params[:name]
      redirect_to articles_path
    else
      render 'index'
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  
  def create
    @user = User.new(user_params)
   
    if @user.save
      redirect_to login_index_path
    else
      render 'index'
    end
  end
  
  private
    def user_params
      params.permit(:name, :pwd)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  
  def create
    @user = User.new(user_params)
   
    if @user.save
      redirect_to logins_path
    else
      render 'index'
    end
  end
  
  private
    def user_params
      params.permit(:name, :pwd)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|

  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :title
    %br
    = f.text_field :title, :maxlength => 10
    %b#article_title_count=10

  %p
    = f.label :text 
    %br
    = f.text_area :text

  %p
    = f.submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing aritcles

= link_to 'New article', new_article_path

%table
  %tr
    %th Title
    %th Text
    %th Id
    %th{:colspan => "3"}
  
  - @article.each do |article|
    %tr
      %td= article.title
      %td= article.text
      %td= article.user.name
      %td= link_to 'Show', article_path(article)
      %td= link_to 'Edit', edit_article_path(article)
      %td= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' }

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p
  %strong Title:
  = @article.title

%p
  %strong Text:
  = @article.text

%h2 Comments
= render @article.comments

%h2#add_comment Add a comment:
= render 'comments/form'

= link_to 'Back', articles_path
= link_to 'Edit', edit_article_path(@article)

app/views/comments/_comment.html.erb
<div id="comment_id_<%=comment.id %>">
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                 method: :delete,
                 class: 'destroy_comment',
                 data: { confirm: 'Are you sure?' } %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<h1>Login</h1>

<%= form_tag('/login/:login_id/login') do %>
  <p>
    <%= label_tag :name %><br>
    <%= text_field_tag [:name] %>
  </p>
 
  <p>
    <%= label_tag :pw %><br>
    <%= text_area_tag [:pwd] %>
  </p>
 
  <p>
    <%= submit_tag %>
  </p>
<% end %>

<%= link_to 'User', user_index_path %>

app/views/logins/index.html.erb
<h1>Login</h1>

<%= form_tag('/logins') do %>
  <p>
    <%= label_tag :name %><br>
    <%= text_field_tag [:name] %>
  </p>
 
  <p>
    <%= label_tag :pw %><br>
    <%= text_area_tag [:pwd] %>
  </p>
 
  <p>
    <%= submit_tag %>
  </p>
<% end %>

<%= link_to 'User', users_path %>

app/views/user/index.html.erb
<h1>Login</h1>

<%= form_tag('/user/:user_id/login') do %>
  <p>
    <%= label_tag :id %><br>
    <%= text_field_tag [:ids] %>
  </p>
 
  <p>
    <%= label_tag :pw %><br>
    <%= text_area_tag [:pwd] %>
  </p>
 
  <p>
    <%= submit_tag %>
  </p>
<% end %>

<%= link_to 'Join', join_index_path %>

app/views/users/index.html.erb
<h1>User</h1>

<%= form_tag('/users') do %>
  <p>
    <%= label_tag :name %><br>
    <%= text_field_tag [:name] %>
  </p>
 
  <p>
    <%= label_tag :pw %><br>
    <%= text_area_tag [:pwd] %>
  </p>
 
  <p>
    <%= submit_tag %>
  </p>
<% end %>

<%= link_to 'Login', logins_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>